services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /honorsuper/mysql-temp:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${mysql_server_password}
      - TZ: Asia/Shanghai
  redis-container:
    image: redis
    volumes:
      - /honorsuper/redis-temp:/data
