version: "3.8"

services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
    networks:
      - common-network
  mysql-container:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - /Users/honorsuper/mysql-temp:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    networks:
      - common-network
  redis-container:
    image: redis
    restart: always
    volumes:
      - /Users/honorsuper/redis-temp:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge